### ISSUE TITLE
TypeError: binding.FSReqWrap is not a constructor

### ISSUE THREAD

**Issue by rcguy** [animetosho/ParPar#16]
Using ParPar installed from git source using node v11.1.0 gives the following error after calculating the par2 recovery data.

```
Multiply method used: XOR JIT (128 bit), 8 threads
Generating 227 MiB recovery data (227 slices) from 2265.38 MiB of data
/home/rcguy/usenet/bin/ParPar/lib/writev.js:14
    var req = new binding.FSReqWrap();
              ^

TypeError: binding.FSReqWrap is not a constructor
    at writev (/home/rcguy/usenet/bin/ParPar/lib/writev.js:14:15)
    at /home/rcguy/usenet/bin/ParPar/lib/par2gen.js:763:7
    at /home/rcguy/usenet/bin/ParPar/lib/par2gen.js:743:13
    at PAR2Gen.<anonymous> (/home/rcguy/usenet/bin/ParPar/lib/par2gen.js:744:7)
    at /home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:1135:9
    at replenish (/home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:1011:17)
    at /home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:1133:5)
    at /home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:1219:16
    at timeLimit (/home/rcguy/usenet/bin/ParPar/node_modules/async/dist/async.js:4997:5)
```

**Comment by animetosho** [comment]
Thanks for reporting the issue!
