### ISSUE TITLE
parpar releases doesnt work with python

### ISSUE THREAD

**Issue by kobayashi90** [animetosho/ParPar#60]
parpar releases doesnt work with python, please fix that..

**Comment by animetosho** [comment]
ParPar is built on NodeJS, not Python.

**Comment by ayniin** [comment]
When i try to call parpar.exe from python as a subprocess or with os.system. I get an error nodejs error.
inspector.js:25
  throw new ERR_INSPECTOR_NOT_AVAILABLE();
  ^

Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
    at inspector.js:25:9
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:26:9)
    at Function.Module._load (internal/modules/cjs/loader.js:679:15)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bootloader.bundle.cdp:8:210
    at Object.<anonymous> (bootloader.bundle.cdp:8:9013)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'ERR_INSPECTOR_NOT_AVAILABLE'
}

**Comment by animetosho** [comment]
I tested the following script on Python 3.10:

```python
import os
print(os.system("parpar.exe --version"))
```

It runs as expected for me. Does it for you? If so, please share the script that causes the above error. If not, do you happen to have something in your environment/config that would trigger Node's inspector to run?

**Comment by ayniin** [comment]
The script:
`import subprocess
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
parpar_path = os.path.join(dir_path,'parpar.exe')
os.system(parpar_path)
subprocess.call([parpar_path])`

I tryed it on 3 different windows installations always the same result. Two were vms and was a fresh install from windows.

**Comment by animetosho** [comment]
Can you get the environment from VSCode? Probably something like `Get-ChildItem env:*` - see if there's `node` options or anything related to 'inspect'.

**Comment by ayniin** [comment]
i Found these:
```VSCODE_INSPECTOR_OPTIONS: :::{"inspectorIpc":"\\\\.\\pipe\\node-cdp.26080-191dd023-0.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"smart","aaPatterns":["y:/#Programming/BAKA_EZPZ_MIGRATION/**","!**/node_modules/**","**/$KNOWN_TOOLS$/**"]}```

**Comment by animetosho** [comment]
Hmm, I don't think that's it unfortunately.  
If you figure how to reproduce the issue outside of VSCode, let me know.
